title: <p align="center"> Bryan Zamora </p>

logo: "images/github.png?raw=true" # your photo (or logo) here

description: > # your text below (remove <br> elements if you don't need line breaks)
  <p align="center">
  <a href="pdf/Official_Bryan_ZM.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/bzamoram/">LinkedIn</a> |
  <a href="https://github.com/bzamoram">GitHub</a>
  </p>
  
  <p align="justify">
  I am pursuing a BA degree in Computer Science (Data Analytics) at Concordia College.
  <br><br>
  I am currently a Digital Innovation Intern at Doosan Bobcat North America. I work with the DataOps team enhancing data accessibility and decision making.
  <br><br>
  </p>
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
#google_analytics: UA-145578661-1 # Google Analytics tracking ID

  

#google_analytics: UA-000000-0 # your Google Analytics tracking ID here (we will come back to this later)
