title: Bryan Zamora
logo: assets/img/headshot.jpg
description: |
  Welcome to my data science portfolio!
  I am a senior college student, passionate about using data 
  to solve real-world challenges.</p></p>
  
 Go ahead and explore my projects in data analysis, machine 
  learning, climate data science, and GIS. 
  This is my safe space to showcase the skills I’m ready to 
  bring to a data science internship.
show_downloads: false
theme: jekyll-theme-minimal


